FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

COPY pyproject.toml uv.lock README.md /app/
RUN uv sync --frozen --no-dev

COPY . /app

CMD ["uv", "run", "uvicorn", "catalog_app.api:app", "--host", "0.0.0.0", "--port", "8000"]
